version: "2.2"

services: 
 napa-app-website:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: napasociety-website
    ports:
      - '3000:3000'
    volumes:
      - ./src/pages:/napa/pages
      - ./public:/napa/public
      - ./styles:/napa/styles

