const Dayoptions = [
  { value: '1 Day', label: '1 Day' },
  { value: '2 Days', label: '2 Days' },
  { value: '3 Days', label: '3 Days' },
  { value: '4 Days', label: '4 Days' },
  { value: '5 Days', label: '5 Days' },
  { value: '6 Days', label: '6 Days' },
  { value: '7 Days', label: '7 Days' },
  { value: '8 Days', label: '8 Days' },
  { value: '9 Days', label: '9 Days' },
  { value: '10 Days', label: '10 Days' },
  { value: '11 Days', label: '11 Days' },
  { value: '12 Days', label: '12 Days' },
  { value: '13 Days', label: '13 Days' },
  { value: '14 Days', label: '14 Days' },
  { value: '15 Days', label: '15 Days' },
  { value: '16 Days', label: '16 Days' },
  { value: '17 Days', label: '17 Days' },
  { value: '18 Days', label: '18 Days' },
  { value: '19 Days', label: '19 Days' },
  { value: '20 Days', label: '20 Days' },
  { value: '21 Days', label: '21 Days' },
  { value: '22 Days', label: '22 Days' },
  { value: '23 Days', label: '23 Days' },
  { value: '24 Days', label: '24 Days' },
  { value: '25 Days', label: '25 Days' },
  { value: '26 Days', label: '26 Days' },
  { value: '27 Days', label: '27 Days' },
  { value: '28 Days', label: '28 Days' },
  { value: '29 Days', label: '29 Days' },
  { value: '30 Days', label: '30 Days' },
];
export { Dayoptions };
