const Dayoptions = [
  { value: 'Day', label: '1 Day' },
  { value: 'Days', label: '2 Days' },
  { value: 'Days', label: '3 Days' },
  { value: 'Days', label: '4 Days' },
  { value: 'Days', label: '5 Days' },
  { value: 'Days', label: '6 Days' },
  { value: 'Days', label: '7 Days' },
  { value: 'Days', label: '8 Days' },
  { value: 'Days', label: '9 Days' },
  { value: 'Days', label: '10 Days' },
  { value: 'Days', label: '11 Days' },
  { value: 'Days', label: '12 Days' },
  { value: 'Days', label: '13 Days' },
  { value: 'Days', label: '14 Days' },
  { value: 'Days', label: '15 Days' },
  { value: 'Days', label: '16 Days' },
  { value: 'Days', label: '17 Days' },
  { value: 'Days', label: '18 Days' },
  { value: 'Days', label: '19 Days' },
  { value: 'Days', label: '20 Days' },
  { value: 'Days', label: '21 Days' },
  { value: 'Days', label: '22 Days' },
  { value: 'Days', label: '23 Days' },
  { value: 'Days', label: '24 Days' },
  { value: 'Days', label: '25 Days' },
  { value: 'Days', label: '26 Days' },
  { value: 'Days', label: '27 Days' },
  { value: 'Days', label: '28 Days' },
  { value: 'Days', label: '29 Days' },
  { value: 'Days', label: '30 Days' },
];
export { Dayoptions };
